<?php
/**
 * @file
 * Contains hooks for the menu modifications.
 */

/**
 * Implements hook_theme().
 */
function menu_theme() {
  return array(
    'mobile_menu_block' => array(
      'variables' => array('menu_block' => NULL, 'btns' => NULL, 'subsite_menu' => NULL, 'header' => NULL),
    ),
    'mobile_menu_toggle_block' => array(
      'variables' => array(),
    ),
    'main_menu_block' => array(
      'variables' => array('menu_block' => NULL)
    ),
  );
}

/**
 * Implements hook_preprocess_hook() for block templates.
 */
function menu_preprocess_block(&$variables) {
  if (isset($variables['attributes']['id']) && !empty($variables['attributes']['id'])) {
    $variables['content']['#attributes']['block'] = $variables['attributes']['id'];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function menu_theme_suggestions_menu_alter(array &$suggestions, array $variables) {
  // Remove the block and replace dashes with underscores in the block ID to
  // use for the hook name.
  if (isset($variables['attributes']['block'])) {
    $hook = str_replace(array('block-', '-'), array('', '_'),    $variables['attributes']['block']);
    $suggestions[] = $variables['theme_hook_original'] . '__' . $hook;
  }
}
